# Generated by Django 3.0.9 on 2021-10-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='description',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='entry',
            new_name='Completed',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='datetime',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='Description',
            field=models.CharField(default='task', max_length=1000),
        ),
    ]
