# Generated by Django 3.0.9 on 2021-10-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211027_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='Completed',
            field=models.CharField(default='No', max_length=65536),
        ),
    ]
